### ISSUE TITLE
MoggiML/CPS.agda issues

### ISSUE THREAD

**Issue by PiotrJander** [gallais/type-scope-semantics#1]
First of all, [this line](https://github.com/gallais/type-scope-semantics/blob/2157dffe4875586da86bb2cd233e0e2adcebf3fc/src/Syntax/MoggiML/CPS.agda#L10) should have `` `→# `` in place of `` `→ ``.

But more importantly, [this line](https://github.com/gallais/type-scope-semantics/blob/2157dffe4875586da86bb2cd233e0e2adcebf3fc/src/Syntax/MoggiML/CPS.agda#L15) produces a logical error.

I am happy to explain the error but it might be simpler to just try to type-check the file.

Agda and stdlib version as required, I'm pretty sure that the error is inherent in the logic of the program.

**Comment by gallais** [comment]
Thanks! That part was not in the paper so I guess I never came back to it when I
changed the notations.

```agda
cps (f `$ t) = cps f `$ cps t
```

looks fine to me: it's the eta-contracted version of the transformation in the [reference paper](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.49.8668&rep=rep1&type=pdf)
(Figure 9 on page 6)

Edit: I should clarify that:

* I introduced `` `→#`` because I noticed that I was systematically using `` `→`` together with `#`
* So the old translation of `` `→`` as pure used to make sense because functions systematically had a type of the form `` a `→ (# b)``
* When transitioning to the combined `` `→#`` the CPS translation of the codomain now needs to explicitly translate the `#` too (hence the call to `#CPS` rather than `CPS`)
